apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure 
spec:
  package: xpkg.upbound.io/upbound/provider-azure:v0.32.0
---
apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
 name: default
spec:
 credentials:
   source: Secret
   secretRef:
     namespace: crossplane-system
     name: azure-creds
     key: creds